"""Command renderers for bioinformatics tools.

Each renderer is a pure function:
  render_*(params, bindings, output_dir) -> RenderedCommand

This gives deterministic, testable command generation without LLM involvement.

Phase 3 additions:
- RenderedCommand carries template_type, command_fingerprint, safety_flags
- render_step() fills these fields automatically from the step type registry
- After RENDERER_REGISTRY is built, each renderer is linked to its
  StepTypeDefinition.renderer so the registry is the single source of truth
"""
from __future__ import annotations

import hashlib
import importlib
import os
import shlex
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class RenderedCommand:
    command_text: str
    # Phase-3 metadata fields (filled by render_step() automatically)
    template_type: str = ""          # step_type, e.g. "qc.fastqc"
    command_fingerprint: str = ""    # short hash of template_type + param keys
    safety_flags: list[str] = field(default_factory=list)
    # Existing fields
    env_vars: dict[str, str] = field(default_factory=dict)
    expected_outputs: list[str] = field(default_factory=list)
    renderer_version: int = 1
    # Phase-5: True when the command was generated by LLM fallback instead of the deterministic renderer
    llm_fallback_used: bool = False


class RendererError(ValueError):
    """Raised when a renderer cannot produce a valid command (missing slot, invalid param)."""


def _require(bindings: dict, slot: str) -> str:
    """Return bindings[slot], raising RendererError if missing."""
    val = bindings.get(slot)
    if not val:
        raise RendererError(f"Required slot '{slot}' is not bound")
    return val


def _threads(params: dict, default: int = 4) -> int:
    return int(params.get("threads", default))


def _compute_fingerprint(template_type: str, params: dict) -> str:
    """Stable short hash of template_type + sorted param keys.

    Used as a cache key for authorization (command_type) and repair memory
    matching.  Intentionally excludes param *values* and file paths so the
    same step run against different samples produces the same fingerprint.
    """
    key = template_type + "::" + ",".join(sorted(params.keys()))
    return hashlib.sha256(key.encode()).hexdigest()[:12]


def _stage_gzip_file(
    source_path: str,
    output_dir: str,
    staged_name: str,
) -> tuple[str, str] | None:
    """Return (prepare_cmd, staged_path) when a gzipped file must be unpacked."""
    if not str(source_path).endswith(".gz"):
        return None
    staged_path = os.path.join(output_dir, staged_name)
    prepare_cmd = f"gzip -dc {shlex.quote(source_path)} > {shlex.quote(staged_path)}"
    return prepare_cmd, staged_path


def _stage_gzip_annotation(annotation_path: str, output_dir: str) -> tuple[str, str] | None:
    """Return (prepare_cmd, staged_path) when a gzipped annotation must be unpacked."""
    return _stage_gzip_file(annotation_path, output_dir, "annotation.gtf")


def _stringify_template_value(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, tuple, set)):
        return " ".join(_stringify_template_value(item) for item in value)
    return str(value)


def _shell_quote_template_value(value: Any) -> str:
    if isinstance(value, (list, tuple, set)):
        return " ".join(shlex.quote(_stringify_template_value(item)) for item in value)
    return shlex.quote(_stringify_template_value(value))


def _format_template(template: str, context: dict[str, str], label: str) -> str:
    try:
        return template.format_map(context)
    except KeyError as exc:
        raise RendererError(f"Template field '{exc.args[0]}' is not available in {label}") from exc


def _build_declarative_context(
    step_type: str,
    params: dict[str, Any],
    bindings: dict[str, Any],
    output_dir: str,
) -> tuple[dict[str, str], dict[str, str]]:
    raw_context = {
        "step_type": step_type,
        "output_dir": output_dir,
    }
    quoted_context = {
        "step_type": step_type,
        "output_dir": shlex.quote(output_dir),
    }

    for source_name, source_values in (
        ("param", params or {}),
        ("binding", bindings or {}),
    ):
        for key, value in source_values.items():
            key_name = str(key)
            raw_value = _stringify_template_value(value)
            quoted_value = _shell_quote_template_value(value)
            raw_context[key_name] = raw_value
            quoted_context[key_name] = quoted_value
            raw_context[f"{source_name}_{key_name}"] = raw_value
            quoted_context[f"{source_name}_{key_name}"] = quoted_value

    return raw_context, quoted_context


def render_declarative_step(
    step_type: str,
    renderer_spec: dict[str, Any],
    params: dict,
    bindings: dict,
    output_dir: str,
) -> RenderedCommand:
    command_template = str(renderer_spec.get("command") or "").strip()
    if not command_template:
        raise RendererError(f"Declarative renderer for '{step_type}' is missing template.command")

    raw_context, quoted_context = _build_declarative_context(step_type, params, bindings, output_dir)

    output_bindings_raw: dict[str, str] = {}
    for slot_name, output_template in (renderer_spec.get("output_bindings") or {}).items():
        slot_key = str(slot_name)
        output_bindings_raw[slot_key] = _format_template(
            str(output_template),
            raw_context,
            f"{step_type} output binding '{slot_key}'",
        )

    for slot_key, raw_value in output_bindings_raw.items():
        quoted_value = shlex.quote(raw_value)
        raw_context[slot_key] = raw_value
        quoted_context[slot_key] = quoted_value
        raw_context[f"output_{slot_key}"] = raw_value
        quoted_context[f"output_{slot_key}"] = quoted_value

    command = _format_template(command_template, quoted_context, f"{step_type} command")
    env_vars = {
        str(key): _format_template(str(value), raw_context, f"{step_type} env var '{key}'")
        for key, value in (renderer_spec.get("env_vars") or {}).items()
    }

    expected_outputs = list(output_bindings_raw.values()) or [output_dir]
    return RenderedCommand(
        command_text=command,
        env_vars=env_vars,
        expected_outputs=expected_outputs,
        renderer_version=int(renderer_spec.get("renderer_version", 1)),
    )


# ---------------------------------------------------------------------------
# qc.fastqc
# ---------------------------------------------------------------------------

def render_fastqc(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    reads = bindings.get("reads") or bindings.get("read1")
    if not reads:
        raise RendererError("Required slot 'reads' (or 'read1') is not bound")

    threads = _threads(params)

    # reads may be a single path or comma-separated list
    if isinstance(reads, list):
        reads_args = " ".join(reads)
    elif "," in str(reads):
        reads_args = reads
    else:
        reads_args = str(reads)

    cmd = f"fastqc {reads_args} -o {output_dir} -t {threads}"
    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[output_dir],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# qc.multiqc
# ---------------------------------------------------------------------------

def render_multiqc(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    input_dir = _require(bindings, "input_dir")
    report_name = params.get("report_name", "multiqc_report")

    cmd = f"multiqc {input_dir} -o {output_dir} -n {report_name}"
    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[os.path.join(output_dir, f"{report_name}.html")],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# trim.fastp
# ---------------------------------------------------------------------------

def render_fastp(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    read1 = _require(bindings, "read1")
    paired_end = bool(params.get("paired_end", False))
    threads = _threads(params)
    quality = int(params.get("quality", 20))
    length_required = int(params.get("length_required", 36))

    sample = Path(read1).name.replace(".fastq.gz", "").replace(".fastq", "").replace(".fq.gz", "").replace(".fq", "")

    out1 = os.path.join(output_dir, f"{sample}_R1_trimmed.fastq.gz")
    json_report = os.path.join(output_dir, f"{sample}_fastp.json")
    html_report = os.path.join(output_dir, f"{sample}_fastp.html")

    cmd = (
        f"fastp -i {read1} -o {out1}"
        f" -q {quality} --length_required {length_required}"
        f" -j {json_report} -h {html_report} -w {threads}"
    )

    if paired_end:
        read2 = bindings.get("read2")
        if not read2:
            raise RendererError("paired_end=true but slot 'read2' is not bound")
        out2 = os.path.join(output_dir, f"{sample}_R2_trimmed.fastq.gz")
        cmd = (
            f"fastp -i {read1} -I {read2} -o {out1} -O {out2}"
            f" -q {quality} --length_required {length_required}"
            f" -j {json_report} -h {html_report} -w {threads}"
        )

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[out1, json_report, html_report],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# align.bwa
# ---------------------------------------------------------------------------

def render_bwa(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    read1 = _require(bindings, "read1")
    index_prefix = _require(bindings, "index_prefix")
    paired_end = bool(params.get("paired_end", False))
    threads = _threads(params, default=8)
    mark_shorter_split_hits = bool(params.get("mark_shorter_split_hits_as_secondary", True))

    sample = Path(read1).name.split(".")[0]
    out_sam = os.path.join(output_dir, f"{sample}.sam")
    split_flag = " -M" if mark_shorter_split_hits else ""

    if paired_end:
        read2 = bindings.get("read2")
        if not read2:
            raise RendererError("paired_end=true but slot 'read2' is not bound")
        cmd = (
            f"bwa mem -t {threads}{split_flag} {index_prefix} {read1} {read2}"
            f" > {out_sam}"
        )
    else:
        cmd = (
            f"bwa mem -t {threads}{split_flag} {index_prefix} {read1}"
            f" > {out_sam}"
        )

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[out_sam],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# align.hisat2
# ---------------------------------------------------------------------------

def render_hisat2(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    read1 = _require(bindings, "read1")
    index_prefix = _require(bindings, "index_prefix")
    paired_end = bool(params.get("paired_end", False))
    threads = _threads(params)
    strandness = params.get("strandness", "unstranded")

    sample = Path(read1).name.split(".")[0]
    out_sam = os.path.join(output_dir, f"{sample}.sam")

    strand_flag = ""
    if strandness == "FR":
        strand_flag = " --rna-strandness FR"
    elif strandness == "RF":
        strand_flag = " --rna-strandness RF"

    if paired_end:
        read2 = bindings.get("read2")
        if not read2:
            raise RendererError("paired_end=true but slot 'read2' is not bound")
        cmd = (
            f"hisat2 -p {threads} -x {index_prefix}"
            f" -1 {read1} -2 {read2}"
            f" -S {out_sam}{strand_flag}"
        )
    else:
        cmd = (
            f"hisat2 -p {threads} -x {index_prefix}"
            f" -U {read1}"
            f" -S {out_sam}{strand_flag}"
        )

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[out_sam],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# align.star
# ---------------------------------------------------------------------------

def render_star(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    read1 = _require(bindings, "read1")
    genome_dir = _require(bindings, "genome_dir")
    paired_end = bool(params.get("paired_end", False))
    threads = _threads(params, default=8)
    two_pass = bool(params.get("two_pass_mode", False))

    sample = Path(read1).name.split(".")[0]
    prefix = os.path.join(output_dir, f"{sample}_")

    prepare_cmds: list[str] = []
    staged_read1 = _stage_gzip_file(read1, output_dir, "read1.fastq")
    if staged_read1:
        prepare_cmd, read1 = staged_read1
        prepare_cmds.append(prepare_cmd)

    reads_arg = read1
    if paired_end:
        read2 = bindings.get("read2")
        if not read2:
            raise RendererError("paired_end=true but slot 'read2' is not bound")
        staged_read2 = _stage_gzip_file(read2, output_dir, "read2.fastq")
        if staged_read2:
            prepare_cmd, read2 = staged_read2
            prepare_cmds.append(prepare_cmd)
        reads_arg = f"{read1} {read2}"

    two_pass_flag = " --twopassMode Basic" if two_pass else ""

    star_cmd = (
        f"STAR --runMode alignReads"
        f" --genomeDir {genome_dir}"
        f" --readFilesIn {reads_arg}"
        f" --outFileNamePrefix {prefix}"
        f" --outSAMtype BAM SortedByCoordinate"
        f" --runThreadN {threads}"
        f"{two_pass_flag}"
    )
    cmd = " && ".join(prepare_cmds + [star_cmd]) if prepare_cmds else star_cmd

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[f"{prefix}Aligned.sortedByCoord.out.bam"],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# quant.featurecounts
# ---------------------------------------------------------------------------

def render_featurecounts(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    annotation_gtf = _require(bindings, "annotation_gtf")
    aligned_bam = bindings.get("aligned_bam")
    if not aligned_bam:
        raise RendererError("Required slot 'aligned_bam' is not bound")

    threads = _threads(params)
    strandness = int(params.get("strandness", 0))
    paired_end = bool(params.get("paired_end", False))
    feature_type = params.get("feature_type", "exon")
    attribute_type = params.get("attribute_type", "gene_id")

    out_counts = os.path.join(output_dir, "counts.txt")

    # aligned_bam can be a single path or list
    if isinstance(aligned_bam, list):
        bam_args = " ".join(aligned_bam)
    else:
        bam_args = str(aligned_bam)

    pe_flag = " -p" if paired_end else ""
    featurecounts_cmd = (
        f"featureCounts -a {annotation_gtf}"
        f" -o {out_counts}"
        f" -T {threads}"
        f" -s {strandness}"
        f" -t {feature_type} -g {attribute_type}"
        f"{pe_flag}"
        f" {bam_args}"
    )
    cmd = featurecounts_cmd
    staged_annotation = _stage_gzip_annotation(annotation_gtf, output_dir)
    if staged_annotation:
        prepare_cmd, staged_path = staged_annotation
        featurecounts_cmd = featurecounts_cmd.replace(
            f"featureCounts -a {annotation_gtf}",
            f"featureCounts -a {staged_path}",
            1,
        )
        cmd = f"{prepare_cmd} && {featurecounts_cmd}"

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[out_counts],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# stats.deseq2
# ---------------------------------------------------------------------------

def render_deseq2(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    counts_matrix = _require(bindings, "counts_matrix")
    sample_metadata_path = str(Path(counts_matrix).with_name("counts.sample_metadata.tsv"))
    alpha = float(params.get("alpha", 0.05))
    min_count = int(params.get("min_count", 10))

    raw_design_factors = params.get("design_factors") or []
    if isinstance(raw_design_factors, str):
        raw_design_factors = [part.strip() for part in raw_design_factors.split(",") if part.strip()]
    design_factors = [str(part).strip() for part in raw_design_factors if str(part).strip()]

    contrast_factor = str(params.get("contrast_factor") or "").strip()
    raw_contrast_pairs = params.get("contrast_pairs") or params.get("contrasts") or []
    contrast_pairs: list[tuple[str, str]] = []
    for item in raw_contrast_pairs:
        numerator = ""
        denominator = ""
        if isinstance(item, dict):
            numerator = str(
                item.get("numerator")
                or item.get("target")
                or item.get("case")
                or ""
            ).strip()
            denominator = str(
                item.get("denominator")
                or item.get("reference")
                or item.get("control")
                or item.get("baseline")
                or ""
            ).strip()
        elif isinstance(item, (list, tuple)) and len(item) >= 2:
            numerator = str(item[0]).strip()
            denominator = str(item[1]).strip()
        elif isinstance(item, str) and ":" in item:
            numerator, denominator = [part.strip() for part in item.split(":", 1)]
        if numerator and denominator:
            contrast_pairs.append((numerator, denominator))

    design_factors_arg = ",".join(design_factors)
    contrast_pairs_arg = ";".join(
        f"{numerator}:{denominator}"
        for numerator, denominator in contrast_pairs
    )

    out_csv = os.path.join(output_dir, "deseq2_results.csv")

    script_path = os.path.join(output_dir, "run_deseq2.R")
    r_script = "\n".join([
        'args <- commandArgs(trailingOnly=TRUE)',
        'counts_path <- args[[1]]',
        'output_path <- args[[2]]',
        'sample_metadata_path <- args[[3]]',
        'alpha <- as.numeric(args[[4]])',
        'min_count <- as.integer(args[[5]])',
        'design_factors_arg <- args[[6]]',
        'contrast_factor_arg <- args[[7]]',
        'contrast_pairs_arg <- args[[8]]',
        'suppressPackageStartupMessages(library(DESeq2))',
        'split_arg <- function(value, sep) {',
        '  if (is.null(value) || is.na(value) || value == "") return(character(0))',
        '  parts <- strsplit(value, sep, fixed=TRUE)[[1]]',
        '  parts[nzchar(parts)]',
        '}',
        'normalize_name <- function(value) {',
        '  value <- tolower(as.character(value))',
        '  gsub("[^a-z0-9]+", "_", value)',
        '}',
        'build_level_alias_map <- function(contrast_levels, sample_meta, contrast_factor_column) {',
        '  alias_map <- list()',
        '  register_alias <- function(alias, level_value) {',
        '    alias_norm <- normalize_name(alias)',
        '    if (!nzchar(alias_norm)) return()',
        '    existing <- alias_map[[alias_norm]]',
        '    if (is.null(existing)) {',
        '      alias_map[[alias_norm]] <<- level_value',
        '    } else if (!is.na(existing) && existing != level_value) {',
        '      alias_map[[alias_norm]] <<- NA_character_',
        '    }',
        '  }',
        '  for (level_value in contrast_levels) {',
        '    register_alias(level_value, level_value)',
        '    tokens <- unlist(strsplit(gsub("[^a-z0-9]+", " ", tolower(level_value)), " +"))',
        '    tokens <- tokens[nzchar(tokens)]',
        '    if (length(tokens) > 1) {',
        '      register_alias(paste(tokens, collapse=""), level_value)',
        '    }',
        '    register_alias(paste(substr(tokens, 1, 1), collapse=""), level_value)',
        '  }',
        '  if ("sample_name" %in% colnames(sample_meta) && contrast_factor_column %in% colnames(sample_meta)) {',
        '    sample_aliases <- sub("([_-](rep)?[0-9]+)+$", "", as.character(sample_meta$sample_name), perl=TRUE)',
        '    sample_aliases <- sub("[_-]+$", "", sample_aliases, perl=TRUE)',
        '    contrast_values <- as.character(sample_meta[[contrast_factor_column]])',
        '    for (idx in seq_along(sample_aliases)) {',
        '      if (is.na(sample_aliases[[idx]]) || is.na(contrast_values[[idx]]) || contrast_values[[idx]] == "") next',
        '      register_alias(sample_aliases[[idx]], contrast_values[[idx]])',
        '    }',
        '  }',
        '  alias_map',
        '}',
        'resolve_contrast_level <- function(requested, contrast_levels, sample_meta, contrast_factor_column, position) {',
        '  if (requested %in% contrast_levels) return(requested)',
        '  requested_norm <- normalize_name(requested)',
        '  contrast_level_norms <- vapply(contrast_levels, normalize_name, character(1))',
        '  direct_match_idx <- match(requested_norm, contrast_level_norms)',
        '  if (!is.na(direct_match_idx)) return(contrast_levels[[direct_match_idx]])',
        '  alias_map <- build_level_alias_map(contrast_levels, sample_meta, contrast_factor_column)',
        '  alias_value <- alias_map[[requested_norm]]',
        '  if (!is.null(alias_value) && !is.na(alias_value)) return(alias_value)',
        '  stop(paste("Unknown contrast", position, ":", requested))',
        '}',
        'resolve_factor_column <- function(requested, available_columns) {',
        '  requested_norm <- normalize_name(requested)',
        '  alias_map <- list(',
        '    condition = c("condition", "condition_label"),',
        '    replicate = c("replicate", "replicate_label")',
        '  )',
        '  candidates <- unique(c(requested, alias_map[[requested_norm]]))',
        '  for (candidate in candidates) {',
        '    if (!is.null(candidate) && candidate %in% available_columns) return(candidate)',
        '  }',
        '  available_norm <- vapply(available_columns, normalize_name, character(1))',
        '  match_idx <- match(requested_norm, available_norm)',
        '  if (!is.na(match_idx)) return(available_columns[[match_idx]])',
        '  for (candidate in candidates) {',
        '    if (is.null(candidate)) next',
        '    candidate_norm <- normalize_name(candidate)',
        '    match_idx <- match(candidate_norm, available_norm)',
        '    if (!is.na(match_idx)) return(available_columns[[match_idx]])',
        '  }',
        '  stop(paste("DESeq2 metadata missing requested factor column:", requested))',
        '}',
        'parse_contrast_pairs <- function(value) {',
        '  raw_pairs <- split_arg(value, ";")',
        '  parsed <- list()',
        '  for (raw_pair in raw_pairs) {',
        '    parts <- strsplit(raw_pair, ":", fixed=TRUE)[[1]]',
        '    if (length(parts) != 2) stop(paste("Invalid contrast pair:", raw_pair))',
        '    parsed[[length(parsed) + 1]] <- c(parts[[1]], parts[[2]])',
        '  }',
        '  parsed',
        '}',
        'counts_df <- read.delim(counts_path, check.names=FALSE, comment.char="#")',
        'annotation_cols <- c("Geneid", "Chr", "Start", "End", "Strand", "Length")',
        'count_cols <- setdiff(colnames(counts_df), annotation_cols)',
        'if (length(count_cols) < 2) stop("DESeq2 requires at least two samples in the counts matrix")',
        'sample_meta <- data.frame(count_column=count_cols, stringsAsFactors=FALSE)',
        'if (file.exists(sample_metadata_path)) {',
        '  sample_meta <- read.delim(sample_metadata_path, sep="\t", check.names=FALSE, stringsAsFactors=FALSE)',
        '  if (!"count_column" %in% colnames(sample_meta)) stop("Sample metadata sidecar missing count_column")',
        '  match_idx <- match(count_cols, sample_meta$count_column)',
        '  if (any(is.na(match_idx))) stop("Sample metadata sidecar missing one or more count columns")',
        '  sample_meta <- sample_meta[match_idx, , drop=FALSE]',
        '} else {',
        '  sample_meta$sample_name <- basename(count_cols)',
        '}',
        'sample_labels <- if ("sample_name" %in% colnames(sample_meta)) as.character(sample_meta$sample_name) else rep("", length(count_cols))',
        'fallback_idx <- which(is.na(sample_labels) | sample_labels == "")',
        'if (length(fallback_idx) > 0) {',
        '  fallback_labels <- basename(count_cols[fallback_idx])',
        '  fallback_labels <- sub("\\\\.bam$", "", fallback_labels)',
        '  fallback_labels <- sub("\\\\.sam$", "", fallback_labels)',
        '  fallback_labels <- sub("_sorted$", "", fallback_labels)',
        '  fallback_labels <- sub("Aligned\\\\.sortedByCoord\\\\.out$", "", fallback_labels)',
        '  sample_labels[fallback_idx] <- fallback_labels',
        '}',
        'sample_meta$sample_name <- sample_labels',
        'if (!"condition" %in% colnames(sample_meta)) sample_meta$condition <- NA_character_',
        'fallback_condition_idx <- which(is.na(sample_meta$condition) | sample_meta$condition == "")',
        'if (length(fallback_condition_idx) > 0 && "condition_label" %in% colnames(sample_meta)) {',
        '  sample_meta$condition[fallback_condition_idx] <- as.character(sample_meta$condition_label[fallback_condition_idx])',
        '}',
        'fallback_condition_idx <- which(is.na(sample_meta$condition) | sample_meta$condition == "")',
        'if (length(fallback_condition_idx) > 0) {',
        '  fallback_condition <- sub("([_-](rep)?[0-9]+)+$", "", sample_labels[fallback_condition_idx])',
        '  fallback_condition <- sub("[_-]+$", "", fallback_condition)',
        '  fallback_condition[fallback_condition == ""] <- sample_labels[fallback_condition_idx][fallback_condition == ""]',
        '  sample_meta$condition[fallback_condition_idx] <- fallback_condition',
        '}',
        'requested_design_factors <- split_arg(design_factors_arg, ",")',
        'if (length(requested_design_factors) == 0) requested_design_factors <- c("condition")',
        'design_columns <- unique(vapply(requested_design_factors, function(factor_name) {',
        '  resolve_factor_column(factor_name, colnames(sample_meta))',
        '}, character(1)))',
        'if (length(design_columns) == 0) stop("DESeq2 requires at least one design factor")',
        'contrast_factor <- contrast_factor_arg',
        'if (!nzchar(contrast_factor)) {',
        '  if ("condition" %in% design_columns) contrast_factor <- "condition" else contrast_factor <- tail(design_columns, 1)',
        '}',
        'contrast_factor_column <- resolve_factor_column(contrast_factor, design_columns)',
        'coldata <- data.frame(row.names=count_cols, sample=sample_labels, stringsAsFactors=FALSE)',
        'effective_design_columns <- character(0)',
        'for (design_column in design_columns) {',
        '  values <- as.character(sample_meta[[design_column]])',
        '  if (any(is.na(values) | values == "")) stop(paste("DESeq2 design factor has missing values:", design_column))',
        '  factor_values <- factor(values)',
        '  if (nlevels(factor_values) < 2) {',
        '    if (design_column == contrast_factor_column) stop(paste("DESeq2 contrast factor must have at least two levels:", design_column))',
        '    next',
        '  }',
        '  coldata[[design_column]] <- factor_values',
        '  effective_design_columns <- c(effective_design_columns, design_column)',
        '}',
        'if (length(effective_design_columns) == 0) stop("DESeq2 requires at least one non-constant design factor")',
        'if (!(contrast_factor_column %in% effective_design_columns)) stop(paste("DESeq2 contrast factor is not available in effective design:", contrast_factor_column))',
        'design_formula_text <- paste("~", paste(effective_design_columns, collapse=" + "))',
        'design_formula <- as.formula(design_formula_text)',
        'count_matrix <- as.matrix(counts_df[, count_cols, drop=FALSE])',
        'storage.mode(count_matrix) <- "integer"',
        'dds <- DESeqDataSetFromMatrix(countData=count_matrix, colData=coldata, design=design_formula)',
        'dds <- dds[rowSums(counts(dds)) >= min_count, ]',
        'if (nrow(dds) == 0) stop("No genes remain after min_count filtering")',
        'dds <- DESeq(dds, quiet=TRUE)',
        'contrast_levels <- levels(coldata[[contrast_factor_column]])',
        'if (length(contrast_levels) < 2) stop("DESeq2 requires at least two levels for the contrast factor")',
        'contrast_pairs <- parse_contrast_pairs(contrast_pairs_arg)',
        'if (length(contrast_pairs) == 0) {',
        '  if (length(contrast_levels) == 2) {',
        '    contrast_pairs <- list(c(contrast_levels[[1]], contrast_levels[[2]]))',
        '  } else {',
        '    contrast_pairs <- combn(contrast_levels, 2, simplify=FALSE)',
        '  }',
        '}',
        'results_list <- lapply(contrast_pairs, function(pair) {',
        '  numerator <- resolve_contrast_level(pair[[1]], contrast_levels, sample_meta, contrast_factor_column, "numerator")',
        '  denominator <- resolve_contrast_level(pair[[2]], contrast_levels, sample_meta, contrast_factor_column, "denominator")',
        '  res <- results(dds, contrast=c(contrast_factor_column, numerator, denominator), alpha=alpha)',
        '  df <- as.data.frame(res)',
        '  df$gene_id <- rownames(df)',
        '  df$contrast <- paste(numerator, "vs", denominator)',
        '  df$contrast_factor <- contrast_factor_column',
        '  df$contrast_numerator <- numerator',
        '  df$contrast_denominator <- denominator',
        '  df$design_formula <- design_formula_text',
        '  df[, c("gene_id", "contrast", "contrast_factor", "contrast_numerator", "contrast_denominator", "design_formula", setdiff(names(df), c("gene_id", "contrast", "contrast_factor", "contrast_numerator", "contrast_denominator", "design_formula")))]',
        '})',
        'results_df <- do.call(rbind, results_list)',
        'results_df <- results_df[order(results_df$padj, na.last=TRUE), ]',
        'write.csv(results_df, output_path, row.names=FALSE)',
    ])

    cmd = (
        f"cat > {shlex.quote(script_path)} <<'EOF'\n"
        f"{r_script}\n"
        f"EOF\n"
        f"Rscript {shlex.quote(script_path)} "
        f"{shlex.quote(counts_matrix)} {shlex.quote(out_csv)} "
        f"{shlex.quote(sample_metadata_path)} {alpha} {min_count} "
        f"{shlex.quote(design_factors_arg)} {shlex.quote(contrast_factor)} {shlex.quote(contrast_pairs_arg)}"
    )
    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[out_csv],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# util.bwa_index
# ---------------------------------------------------------------------------

def render_bwa_index(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    fasta = _require(bindings, "reference_fasta")
    prefix_name = str(params.get("prefix_name") or "genome").strip() or "genome"
    prefix = os.path.join(output_dir, "bwa_index", prefix_name)
    os.makedirs(os.path.dirname(prefix), exist_ok=True)
    cmd = f"bwa index -p {prefix} {fasta}"
    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[prefix + ".bwt"],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# util.star_genome_generate
# ---------------------------------------------------------------------------

def render_star_genome_generate(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    fasta = _require(bindings, "reference_fasta")
    threads = _threads(params)
    genome_sa_nbases = int(params.get("genome_sa_index_nbases") or 14)
    genome_dir = os.path.join(output_dir, "star_genome")
    os.makedirs(genome_dir, exist_ok=True)

    parts = [
        "STAR",
        "--runMode genomeGenerate",
        f"--genomeDir {genome_dir}",
        f"--genomeFastaFiles {fasta}",
        f"--runThreadN {threads}",
        f"--genomeSAindexNbases {genome_sa_nbases}",
    ]

    gtf = bindings.get("annotation_gtf")
    prepare_cmds: list[str] = []
    staged_annotation = _stage_gzip_annotation(gtf, output_dir) if gtf else None
    if staged_annotation:
        prepare_cmd, staged_path = staged_annotation
        prepare_cmds.append(prepare_cmd)
        gtf = staged_path
    if gtf:
        parts.append(f"--sjdbGTFfile {gtf}")

    star_cmd = " ".join(parts)
    cmd = " && ".join(prepare_cmds + [star_cmd]) if prepare_cmds else star_cmd
    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[os.path.join(genome_dir, "SA")],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# util.hisat2_build
# ---------------------------------------------------------------------------

def render_hisat2_build(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    fasta = _require(bindings, "reference_fasta")
    threads = _threads(params)
    prefix = os.path.join(output_dir, "hisat2_index", "genome")
    os.makedirs(os.path.dirname(prefix), exist_ok=True)
    cmd = f"hisat2-build -p {threads} {fasta} {prefix}"
    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[prefix + ".1.ht2"],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# util.samtools_sort
# ---------------------------------------------------------------------------

def render_samtools_sort(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    input_file = bindings.get("input_sam_or_bam") or bindings.get("aligned_bam")
    if not input_file:
        raise RendererError("Required slot 'input_sam_or_bam' is not bound")

    threads = _threads(params)
    mem = params.get("memory_per_thread", "768M")

    sample = Path(input_file).name.rsplit(".", 1)[0]
    out_bam = os.path.join(output_dir, f"{sample}_sorted.bam")

    cmd = (
        f"samtools sort -@ {threads} -m {mem}"
        f" -o {out_bam} {input_file}"
    )

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[out_bam],
        renderer_version=renderer_version,
    )


# ---------------------------------------------------------------------------
# util.samtools_index
# ---------------------------------------------------------------------------

def render_samtools_index(
    params: dict, bindings: dict, output_dir: str, renderer_version: int = 1
) -> RenderedCommand:
    sorted_bam = _require(bindings, "sorted_bam")
    threads = _threads(params)

    cmd = f"samtools index -@ {threads} {sorted_bam}"
    bai = sorted_bam + ".bai"

    return RenderedCommand(
        command_text=cmd,
        expected_outputs=[bai],
        renderer_version=renderer_version,
    )


def ensure_renderers_loaded() -> None:
    """Re-link built-in renderers after unusual reload/import ordering."""
    from tune.core.registry import ensure_registry_loaded, get_step_type as _get_step_type

    ensure_registry_loaded()

    builtins = {
        "qc.fastqc": render_fastqc,
        "qc.multiqc": render_multiqc,
        "trim.fastp": render_fastp,
        "align.bwa": render_bwa,
        "align.hisat2": render_hisat2,
        "align.star": render_star,
        "quant.featurecounts": render_featurecounts,
        "stats.deseq2": render_deseq2,
        "util.bwa_index": render_bwa_index,
        "util.hisat2_build": render_hisat2_build,
        "util.star_genome_generate": render_star_genome_generate,
        "util.samtools_sort": render_samtools_sort,
        "util.samtools_index": render_samtools_index,
    }
    missing = [step_type for step_type in builtins if step_type not in RENDERER_REGISTRY]
    if missing:
        importlib.import_module("tune.core.registry.steps")
        RENDERER_REGISTRY.update(builtins)

    for step_type, fn in builtins.items():
        defn = _get_step_type(step_type)
        if defn is not None and defn.renderer is None:
            defn.renderer = fn


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

RENDERER_REGISTRY: dict[str, callable] = {
    "qc.fastqc":            render_fastqc,
    "qc.multiqc":           render_multiqc,
    "trim.fastp":           render_fastp,
    "align.bwa":            render_bwa,
    "align.hisat2":         render_hisat2,
    "align.star":           render_star,
    "quant.featurecounts":  render_featurecounts,
    "stats.deseq2":        render_deseq2,
    "util.bwa_index":       render_bwa_index,
    "util.hisat2_build":         render_hisat2_build,
    "util.star_genome_generate": render_star_genome_generate,
    "util.samtools_sort":   render_samtools_sort,
    "util.samtools_index":  render_samtools_index,
}

# Phase 3: link each renderer to its StepTypeDefinition so the registry is
# the single source of truth.  This runs at import time; import order is
# safe because registry/steps.py has no dependency on renderer.
from tune.core.registry import get_step_type as _get_step_type  # noqa: E402
for _step_type, _fn in RENDERER_REGISTRY.items():
    _defn = _get_step_type(_step_type)
    if _defn is not None:
        _defn.renderer = _fn


def render_step(
    step_type: str,
    params: dict,
    bindings: dict,
    output_dir: str,
) -> RenderedCommand:
    """Dispatch to the appropriate renderer. Raises RendererError on unknown step_type.

    Phase-3 behaviour: prefers defn.renderer (set at import time) over the
    static RENDERER_REGISTRY dict, then fills template_type, command_fingerprint,
    and safety_flags on the returned RenderedCommand automatically.
    """
    from tune.core.registry import ensure_registry_loaded, get_step_type

    ensure_registry_loaded()
    ensure_renderers_loaded()
    defn = get_step_type(step_type)

    renderer_fn = (defn.renderer if defn and defn.renderer else None) or RENDERER_REGISTRY.get(step_type)
    if renderer_fn is None and defn and defn.renderer_spec:
        result = render_declarative_step(step_type, defn.renderer_spec, params, bindings, output_dir)
    elif renderer_fn is None:
        raise RendererError(
            f"No renderer registered for step_type '{step_type}'. "
            f"Available: {sorted(RENDERER_REGISTRY)}"
        )
    else:
        result = renderer_fn(params, bindings, output_dir)

    # Fill Phase-3 metadata fields if not already set by the renderer
    if not result.template_type:
        result.template_type = step_type
    if not result.command_fingerprint:
        result.command_fingerprint = _compute_fingerprint(step_type, params)
    if not result.safety_flags and defn and defn.safety_policy.safety_flags:
        result.safety_flags = list(defn.safety_policy.safety_flags)

    return result
