"""Materialize unknown step types from plan-provided dynamic specs."""
from __future__ import annotations

import logging
import importlib
import re
from pathlib import Path
from typing import Any

import yaml

from tune.core.registry.custom_steps import STEP_SPEC_DIR, build_step_definition_from_payload

log = logging.getLogger(__name__)

_SAFE_NAME_RE = re.compile(r"[^a-zA-Z0-9_.-]+")


def _resolve_analysis_dir() -> Path | None:
    import os

    analysis_dir_env = os.environ.get("TUNE_ANALYSIS_DIR")
    if analysis_dir_env:
        return Path(analysis_dir_env).expanduser().resolve()
    try:
        from tune.core.config import get_config

        return get_config().analysis_dir
    except Exception:
        return None


def _normalize_dynamic_step_payload(step: dict[str, Any], dynamic_spec: dict[str, Any]) -> dict[str, Any]:
    payload = dict(dynamic_spec)
    payload["step_type"] = step.get("step_type")
    if step.get("display_name"):
        payload.setdefault("display_name", step.get("display_name"))
    if step.get("supports_fan_out") is True:
        payload.setdefault("fanout_mode", "per_sample")
    elif step.get("supports_fan_out") is False:
        payload.setdefault("fanout_mode", "none")
    payload.setdefault("params_schema", {"type": "object", "properties": {}})
    payload.setdefault("pixi_packages", [])
    payload.setdefault("input_slots", [])
    payload.setdefault("output_slots", [])
    payload.setdefault("repair_policy", {})
    payload.setdefault("safety_policy", {})
    return payload


def _persist_dynamic_step_payload(payload: dict[str, Any], analysis_dir: Path | None) -> None:
    if analysis_dir is None:
        return
    spec_dir = analysis_dir / STEP_SPEC_DIR / "autogenerated"
    spec_dir.mkdir(parents=True, exist_ok=True)
    step_type = str(payload.get("step_type") or "dynamic.step")
    safe_name = _SAFE_NAME_RE.sub("_", step_type).strip("._") or "dynamic_step"
    path = spec_dir / f"{safe_name}.yaml"
    path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True))


def materialize_dynamic_step_types(steps: list[dict[str, Any]]) -> list[str]:
    """Register and persist dynamic step definitions embedded in plan steps."""
    from tune.core.registry import all_step_types, get_step_type

    steps_module = importlib.import_module("tune.core.registry.steps")

    issues: list[str] = []
    analysis_dir = _resolve_analysis_dir()
    known_types = set(all_step_types())

    for step in steps:
        step_type = str(step.get("step_type") or "").strip()
        if not step_type or step_type in known_types or get_step_type(step_type) is not None:
            continue

        dynamic_spec = step.get("dynamic_spec")
        if not isinstance(dynamic_spec, dict):
            continue

        try:
            payload = _normalize_dynamic_step_payload(step, dynamic_spec)
            defn = build_step_definition_from_payload(payload, steps_module)
            steps_module.register_custom(defn)
            _persist_dynamic_step_payload(payload, analysis_dir)
            known_types.add(step_type)
            log.info("Materialized dynamic step_type '%s' from plan dynamic_spec", step_type)
        except Exception as exc:
            issues.append(f"Step '{step.get('step_key') or step_type}' dynamic_spec error: {exc}")

    return issues
